server:
 port: 8082

spring:
 application:
  name: WorkHub Task Service
 data:
  mongodb:
   uri: ${MONGO_DATABASE_URL:mongodb+srv://manish:fBxLDjziEgA6CCEn@vrv.tzoxj.mongodb.net/?retryWrites=true&w=majority&appName=vrv}
   database: ${MONGO_DATABASE_TABLE:Task}